package app.interaction;

public enum Noun {
    KNIFE, COFFEE_POT, BEER_BOTTLE, LEFT, RIGHT, UP, DOWN, NONE, BUTTON, ROOM, DOOR, LIGHT, MIRROR, TOILET, FAUCET, SELF, CABINETS, BAR, FRIDGE, PINBALL, CLOTHES, WHITEBOARD, MAN, COMPUTER, TERMINAL, PUSH;
}
